/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "MockCryptoKitties",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCryptoKitties__factory>;
    getContractFactory(
      name: "ZombieAttack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieAttack__factory>;
    getContractFactory(
      name: "ZombieFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieFactory__factory>;
    getContractFactory(
      name: "KittyInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KittyInterface__factory>;
    getContractFactory(
      name: "ZombieFeeding",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieFeeding__factory>;
    getContractFactory(
      name: "ZombieHelper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieHelper__factory>;
    getContractFactory(
      name: "ZombieOwnership",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieOwnership__factory>;
    getContractFactory(
      name: "ZombieSkills",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZombieSkills__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "MockCryptoKitties",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCryptoKitties>;
    getContractAt(
      name: "ZombieAttack",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieAttack>;
    getContractAt(
      name: "ZombieFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieFactory>;
    getContractAt(
      name: "KittyInterface",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.KittyInterface>;
    getContractAt(
      name: "ZombieFeeding",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieFeeding>;
    getContractAt(
      name: "ZombieHelper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieHelper>;
    getContractAt(
      name: "ZombieOwnership",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieOwnership>;
    getContractAt(
      name: "ZombieSkills",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZombieSkills>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "MockCryptoKitties",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockCryptoKitties>;
    deployContract(
      name: "ZombieAttack",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieAttack>;
    deployContract(
      name: "ZombieFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieFactory>;
    deployContract(
      name: "KittyInterface",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KittyInterface>;
    deployContract(
      name: "ZombieFeeding",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieFeeding>;
    deployContract(
      name: "ZombieHelper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieHelper>;
    deployContract(
      name: "ZombieOwnership",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieOwnership>;
    deployContract(
      name: "ZombieSkills",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieSkills>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "MockCryptoKitties",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockCryptoKitties>;
    deployContract(
      name: "ZombieAttack",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieAttack>;
    deployContract(
      name: "ZombieFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieFactory>;
    deployContract(
      name: "KittyInterface",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.KittyInterface>;
    deployContract(
      name: "ZombieFeeding",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieFeeding>;
    deployContract(
      name: "ZombieHelper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieHelper>;
    deployContract(
      name: "ZombieOwnership",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieOwnership>;
    deployContract(
      name: "ZombieSkills",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZombieSkills>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
