/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { MockCryptoKitties } from "./contracts/mocks/MockCryptoKitties";
export { MockCryptoKitties__factory } from "./factories/contracts/mocks/MockCryptoKitties__factory";
export type { ZombieAttack } from "./contracts/mocks/ZombieAttack";
export { ZombieAttack__factory } from "./factories/contracts/mocks/ZombieAttack__factory";
export type { ZombieFactory } from "./contracts/mocks/ZombieFactory";
export { ZombieFactory__factory } from "./factories/contracts/mocks/ZombieFactory__factory";
export type { KittyInterface } from "./contracts/mocks/ZombieFeeding.sol/KittyInterface";
export { KittyInterface__factory } from "./factories/contracts/mocks/ZombieFeeding.sol/KittyInterface__factory";
export type { ZombieFeeding } from "./contracts/mocks/ZombieFeeding.sol/ZombieFeeding";
export { ZombieFeeding__factory } from "./factories/contracts/mocks/ZombieFeeding.sol/ZombieFeeding__factory";
export type { ZombieHelper } from "./contracts/mocks/ZombieHelper";
export { ZombieHelper__factory } from "./factories/contracts/mocks/ZombieHelper__factory";
export type { ZombieOwnership } from "./contracts/mocks/ZombieOwnership";
export { ZombieOwnership__factory } from "./factories/contracts/mocks/ZombieOwnership__factory";
export type { ZombieSkills } from "./contracts/mocks/ZombieSkills";
export { ZombieSkills__factory } from "./factories/contracts/mocks/ZombieSkills__factory";
