/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as zombieFeedingSol from "./ZombieFeeding.sol";
export { MockCryptoKitties__factory } from "./MockCryptoKitties__factory";
export { ZombieAttack__factory } from "./ZombieAttack__factory";
export { ZombieFactory__factory } from "./ZombieFactory__factory";
export { ZombieHelper__factory } from "./ZombieHelper__factory";
export { ZombieOwnership__factory } from "./ZombieOwnership__factory";
export { ZombieSkills__factory } from "./ZombieSkills__factory";
