/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockCryptoKitties,
  MockCryptoKittiesInterface,
} from "../../../contracts/mocks/MockCryptoKitties";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_id",
        type: "uint256",
      },
    ],
    name: "getKitty",
    outputs: [
      {
        internalType: "bool",
        name: "isGestating",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "isReady",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "cooldownIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nextActionAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "siringWithId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "birthTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "matronId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sireId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "generation",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "genes",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610157806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063e98b7f4d14610030575b600080fd5b61004361003e3660046100e1565b610093565b604080519a15158b5298151560208b0152978901969096526060880194909452608087019290925260a086015260c085015260e08401526101008301526101208201526101400160405180910390f35b60008080808080808080806701b69b4ba630f3008b156100ba576100b78c826100fa565b90505b60009c60019c508d9b508b9a508a9950620f424098508997508796508c9550909350915050565b6000602082840312156100f357600080fd5b5035919050565b8082018082111561011b57634e487b7160e01b600052601160045260246000fd5b9291505056fea26469706673582212208d4973e498483e1def89794723933453abae1f6ff57648b2c2405ee2639a4b7064736f6c63430008180033";

type MockCryptoKittiesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockCryptoKittiesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockCryptoKitties__factory extends ContractFactory {
  constructor(...args: MockCryptoKittiesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockCryptoKitties & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockCryptoKitties__factory {
    return super.connect(runner) as MockCryptoKitties__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockCryptoKittiesInterface {
    return new Interface(_abi) as MockCryptoKittiesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockCryptoKitties {
    return new Contract(address, _abi, runner) as unknown as MockCryptoKitties;
  }
}
