/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zombieFeedingSol from "./ZombieFeeding.sol";
export type { zombieFeedingSol };
export type { MockCryptoKitties } from "./MockCryptoKitties";
export type { ZombieAttack } from "./ZombieAttack";
export type { ZombieFactory } from "./ZombieFactory";
export type { ZombieHelper } from "./ZombieHelper";
export type { ZombieOwnership } from "./ZombieOwnership";
export type { ZombieSkills } from "./ZombieSkills";
